services:
  talentmanagementapi.webapi:
    image: ${DOCKER_REGISTRY-}talentmanagementapiwebapi
    build:
      context: ../..
      dockerfile: ApiResources/TalentManagement-API/TalentManagementAPI.WebApi/Dockerfile
